# NumPy 학습

1. 파이썬에서 배열을 사용하기 위한 수치 해석용 표준 패키지
- 적은 메모리로 데이터를 빠르게 처리할 수 있음
- 다차원의 배열 자료구조 클래스인 ndarray 클래스를 지원하며 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용
- 배열 연산은 C로 구현된 내부 반복문을 사용하기 때문에 파이썬 반복문에 비해 속도가 빠름
- 벡터화 연산(vectorized operation)을 이용하여 간단한 코드로도 복잡한 선형 대수 연산을 수행할 수 있음
- 배열 인덱싱(array indexing)을 사용한 질의(Query) 기능을 이용하여 간단한 코드로도 복잡한 수식을 계산할 수 있음
- C언어의 배열처럼 연속적인 메모리 배치를 하기 때문에 모든 원소가 같은 자료형이어야 함
- 이러한 제약사항이 있는 대신 원소에 대한 접근과 반복문 실행이 빨라짐
- ndarray 는 N-dimensional Array의 약자로 1차원, 2차원,  3차원 배열 등의 다차원 배열 자료 구조를 지원
- **2차원 배열은 행렬(matrix)** 이라고 하는데 행렬에서는 가로줄을 행 *(row)이라고 하고 세로줄을 *열(column)이라 함
- 다차원 배열 : 리스트의 리스트(list of list)를 이용하면 2차원 배열을 생성할 수 있음. 
- 안쪽 리스트의 길이는 행렬의 열의 수 즉, 가로 크기가 되고 바깥쪽 리스트의 길이는 행렬의 행의 수, 즉 세로 크기를 의미
- url<br>
http://www.numpy.org/<br>
https://docs.scipy.org/doc/numpy-1.15.0/reference/index.html#reference


### NumPy 패키지 import

> NumPy는 np라는 이름으로 임포트하는 것이 관례

In [1]:
!pip show numpy

Name: numpy
Version: 1.15.1
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: c:\users\playdata\anaconda3\lib\site-packages
Requires: 
Required-by: 


In [2]:
import numpy as np

### Numpy 필요성 인지를 위한 간략 코드
- 반복문 실행 시간 비교하기

In [3]:
numpyArray = np.arange(10000000)
plist = list( range(10000000) )

In [4]:
%time for _ in range(10): numpyArray = numpyArray * 2
%time for _ in range(10): plist = [x * 2 for x in plist]

Wall time: 278 ms
Wall time: 12.6 s


### NumPy 모듈을 사용한 1차원 배열 만들기

- array 함수에 리스트를 넣으면 배열로 변환

In [5]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(data)
type(data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


list

In [19]:
# 정수 배열
data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(data)


[0 1 2 3 4 5 6 7 8 9]


In [20]:
type(data)

numpy.ndarray

In [21]:
data.ndim

1

In [22]:
data.shape
print(data*data.T)

[ 0  1  4  9 16 25 36 49 64 81]


In [16]:
print(data.reshape(1,10))

[[0 1 2 3 4 5 6 7 8 9]]


[ 0  1  4  9 16 25 36 49 64 81]


In [23]:
#dtype을 이용한 실수 배열 타입
data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=float)



In [24]:
type(data)

numpy.ndarray

### NumPy 모듈을 사용한  2차원 배열 만들기

In [26]:
data = np.array([[1,2,3],[4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
data.ndim

2

In [28]:
data.shape

(2, 3)

In [29]:
data[0], data[1]

(array([1, 2, 3]), array([4, 5, 6]))

In [30]:
data[0][1]

2

In [33]:
data[1][2] = 60
data

array([[ 1,  2,  3],
       [ 4,  5, 60]])

In [34]:
# 배열의 행의 개수
len(data)

2

In [35]:
# 0행의 열의 개수
len(data[0])

3

In [36]:
#오류 len(data[0][0])

TypeError: object of type 'numpy.int32' has no len()

### NumPy 모듈을 사용한  3차원 배열 만들기

리스트의 리스트의 리스트를 이용하면 3차원 배열도 생성할 수 있음<br>
크기를 나타낼 때는 가장 **바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로** 표시<br>
예를 들어 2 x 3 x 4 배열은 다음과 같이 구성

In [38]:
data = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
data, data.ndim, data.shape

(array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]), 3, (2, 3, 4))

3차원 배열의 행, 열, 깊이

In [40]:
data[1][1][0] = 1717
data

array([[[   1,    2,    3,    4],
        [   5,    6,    7,    8],
        [   9,   10,   11,   12]],

       [[  13,   14,   15,   16],
        [1717,   18,   19,   20],
        [  21,   22,   23,   24]]])

### NumPy 함수를 사용하여 배열 생성하기

1. 규모가 큰 배열의 경우에는 NumPy에 내장된 루틴을 사용해서 처음부터 배열을 생성하는 것이 효율적
- 주요 함수<br>
a. zeros, ones <br>
b. zeros_like, ones_like<br>
c. empty<br>
d. arange : 특정한 규칙에 따라 증가하는 수열 만들기<br>
e. linspace, logspace : 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할<br>
f. rand, randn<br>

In [42]:
#0 값으로 정수 배열 만들기
data = np.zeros(10, dtype=int)

In [43]:
data.ndim

1

In [44]:
data.shape

(10,)

In [47]:
#? 1값으로 10개의 데이터를 보유한 numpy 배열 만들고 출력
# dtype=int 1의 정수, 생략시 1.0의 실수
data = np.ones(10, dtype=int)
data

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [48]:
#다차원 배열
#2행 3열, int
data = np.zeros((2,3), dtype=int)

In [50]:
data

array([[0, 0, 0],
       [0, 0, 0]])

In [52]:
data[1][2] = 100
data

array([[  0,   0,   0],
       [  0,   0, 100]])

In [53]:
#2행 3열의 data 변수의 열의 값 3이 출력되게 하세요
len(data[0])

3

In [56]:
# 5로 채워진 3x5 배열 구성하기
data = np.full((3,5) , 5)
data

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [58]:
# 0~10까지의 범위 내에서 2씩 증가되는 배열 만들
data = np.arange(0, 10, 2)
data

array([0, 2, 4, 6, 8])

In [59]:
# (0.1 ~ 1 10)
np.linspace(0, 5,2)

array([0., 5.])

In [60]:
np.linspace(0, 10,2)

array([ 0., 10.])

In [61]:
np.linspace(0, 10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [63]:
# (0.1 ~ 1 10)
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [65]:
# 0~1 사이의 난수 발생하는함수
np.random.random((3,3))

array([[0.55879483, 0.47211697, 0.49413861],
       [0.57199143, 0.11371322, 0.21832979],
       [0.13804912, 0.83399412, 0.80085069]])

In [67]:
# 0~10까지의 임의의 정수로 3X3 배열 만들기
np.random.randint(0, 10, (3,3))

array([[9, 8, 6],
       [3, 0, 1],
       [6, 7, 6]])

- np.eye() : 단위 행렬 구성 
- [API doc](https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html)

In [54]:
# 3x3 단위 행렬 만들기
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## NumPy 배열의 기초

### 배열 속성 지정

> 각 배열이 보유하고 있는 속성들

1. ndim : 차원의 개수<br>
- shape : 각 차원의 크기
- size : 전체 배열 크기

<br>
> randint(maxno, size=(nxm)) or randint(minno, maxno, (nxm))<br>
-정수형의 난수 발생 함수

In [ ]:
# 동일한 난수 배열이 생성되도록 시드값 설정
np.random.seed(0)

정수 범위내의 난수 발생해서 1차원~3차원 배열 생성해 보기

In [84]:
x1 = np.random.randint(10, size=6) # 1차원 배열
x2 = np.random.randint(10, size=(3, 4)) # 2차원 배열
x3 = np.random.randint(10, size=(3, 4, 5))# 3차원 배열
x1, x2, x3

(array([7, 9, 2, 0, 5, 9]), array([[3, 6, 8, 7],
        [9, 2, 3, 7],
        [4, 8, 9, 8]]), array([[[2, 7, 0, 5, 4],
         [7, 1, 2, 7, 4],
         [4, 5, 7, 4, 4],
         [7, 1, 7, 1, 7]],
 
        [[6, 0, 3, 7, 1],
         [2, 8, 0, 4, 6],
         [4, 5, 5, 7, 0],
         [5, 3, 2, 6, 5]],
 
        [[8, 2, 9, 8, 9],
         [6, 3, 7, 3, 9],
         [7, 3, 8, 5, 5],
         [5, 4, 6, 3, 7]]]))

배열 indexing : 단일 요소 접근하기

### 배열의 색인과  슬라이싱 
> x[start : stop : step] <br>
하위 배열에 접근하기

In [87]:
data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int)
data2 = data[1:].reshape(3,3)
data2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
x1 = data2[2:2]
x1.shape

(0, 3)

In [94]:
x2 = data2[:2,1:] # 2행까지 1번인덱스부터
x2

array([[2, 3],
       [5, 6]])

In [98]:
data2[:,1:2]

array([[2],
       [5],
       [8]])

### 데이터 복사 이해하기

> NumPy는 대용량 데이터 처리를 염두해 두고 설계되었기 때문에 NumPy가 데이터 복사를 남발할 경우 성능과 메모리 문제 발생 가능성이 있음
<br>
별도의 복사된 데이터를 활용하고자 할 경우 copy() 함수 사용

copy() 함수를 사용하지 않은 경우

In [112]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
x[5]

5

In [114]:
x[3:8]

array([3, 4, 5, 6, 7])

In [115]:
#array([0,1,2,3,4,30,30,30, 8,9])
x[5:8] = 30
x

array([ 0,  1,  2,  3,  4, 30, 30, 30,  8,  9])

copy() 함수를 사용한 경우

In [116]:
y = x[5:8]
y

array([30, 30, 30])

In [117]:
y[0] = 100
y

array([100,  30,  30])

In [119]:
x

array([  0,   1,   2,   3,   4, 100,  30,  30,   8,   9])

In [120]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
y = x[5:8].copy()
y

array([5, 6, 7])

In [122]:
y[0] = 100
y

array([100,   6,   7])

In [123]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> 다차원 하위 배열

In [124]:
x2 = np.random.randint(10, size=(3,4)) # 2차원 배열
x2

array([[1, 0, 3, 6],
       [8, 0, 8, 1],
       [2, 2, 9, 4]])

In [127]:
'''
1. x2가 몇차월 배열? 2차원
2. x2[0]이 몇차원 배열? 1차원
3. x2의 구조(shape) 3x4
4. x2[0]의 구조 1x4
5. x2 모든 1행, 모든 4열의 데이터를 출력 x2[0][3]
6. x2의 모든 2행까지의 모든 4열
7. x2의 모든 행의 0~2 컬럼값들만 출력
'''

'\n1. x2가 몇차월 배열? 2차원\n2. x2[0]이 몇차원 배열? 1차원\n3. x2의 구조(shape) 3x4\n4. x2[0]의 구조 1x4\n5. x2 모든 1행, 모든 4열의 데이터를 출력 x2[0][3]\n6. x2의 모든 2행까지의 모든 4열\n7. x2의 모든 행의 0~2 컬럼값들만 출력\n'

In [131]:
x2.ndim

2

In [133]:
x2[0].ndim

1

In [134]:
x2.shape

(3, 4)

In [135]:
x2[0].shape

(4,)

In [136]:
x2[0,:]

array([1, 0, 3, 6])

In [138]:
x2[:,3]

array([6, 1, 4])

In [139]:
x2[:1,:]

array([[1, 0, 3, 6]])

In [144]:
x2[:,:3]

array([[1, 0, 3],
       [8, 0, 8],
       [2, 2, 9]])

> 배열의 재 구조화

In [145]:
# reshape() 메소드
data = np.arange(1, 10)
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
x = data.reshape(3,3)

In [158]:
x.shape, x.ndim

((3, 3), 2)

In [159]:
data = np.array([1, 2, 3])

In [160]:
data.ndim

1

In [161]:
data.shape

(3,)

In [170]:
x = data.reshape((3,1))
x

array([[1],
       [2],
       [3]])

In [171]:
x.ndim

2

In [172]:
x.shape

(3, 1)

> 배열 연결 및 분할
- 여러 배열을  하나로 결합 또는 하나의 배열을 여러 개의 배열로 분할하기
- np.concatenate(numpy의 배열과 python의 list 결합도 가능)
- np.vstack, np.hstack 루틴을 이용해 두 배열 결합 및 연결

1차원 배열간의 결합

In [174]:
x = np.array([1,2,3])
y = np.array([3,2,1])
x, y

(array([1, 2, 3]), array([3, 2, 1]))

In [181]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [182]:
type(x)

numpy.ndarray

In [183]:
# python의 list
z = [5,6,7]
type(z)

list

In [185]:
data = np.concatenate([x,y,z])
data, type(data)

(array([1, 2, 3, 3, 2, 1, 5, 6, 7]), numpy.ndarray)

2차원 배열간의 결합

In [186]:
data = np.array([[1,2,3],[5,6,7]])
data

array([[1, 2, 3],
       [5, 6, 7]])

In [187]:
data.ndim, data.shape

(2, (2, 3))

In [189]:
# 2차원 배열 두가지로 새로운 numpy 배열 생성
data2 = np.array([data, data])
data2, data2.shape

(array([[[1, 2, 3],
         [5, 6, 7]],
 
        [[1, 2, 3],
         [5, 6, 7]]]), (2, 2, 3))

In [190]:
data2[0]

array([[1, 2, 3],
       [5, 6, 7]])

In [196]:
# 이미 존재하는 컬럼에 결합해서 컬럼이 추가
data2 = np.concatenate([data, data], axis=1)
data2.shape

(2, 6)

In [197]:
# 이미 존재하는 로우에 결합해서 로우가 추가
data3 = np.concatenate([data, data], axis=0)
data3.shape

(4, 3)

> 혼합된 차원의 배열
- 행의 수나 열의 수가 같은 두개 이상의 배열을 연결하여 더 큰 배열 생성하는  명령어
- np.vstack : 수직 스택, vertical stack, 컬럼 개수는 맞아야 함 <br>
- np.hstack : 수평 스택, horizontal stack, 하나의 컬럼에 속해있는 row개수는 동일해야 함
- dstack : 제 3의 축, 즉 행이나 열이 아닌 깊이 방향으로 배열을 결합, 가장 안쪽의 원소 차원이 증가
- stack : 사용자가 지정한 차원(축)으로 연결
- r_ : hstack과 함께 배열을 좌우로 연결
- c_ : 배열의 차원을 증가시킨 후 좌우로 연결, 가령 1차원 배열을 연결하면 2차원 배열이 됨
- tile : 동일한 배열을 반복하여 연결

In [200]:
x = np.array([1,2,3])
data = np.array([[5,6,7], [8,9,10]])
x, x.shape, x.ndim, data, data.shape, data.ndim

(array([1, 2, 3]), (3,), 1, array([[ 5,  6,  7],
        [ 8,  9, 10]]), (2, 3), 2)

In [203]:
#배열을 수직으로 추가 하는 함수
np.vstack([x,data])

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [202]:
np.vstack([data,x])

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [ 1,  2,  3]])

In [204]:
x

array([1, 2, 3])

In [213]:
data

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [214]:
x.ndim, data.ndim

(1, 2)

In [224]:
np.hstack([x,data])

ValueError: all the input arrays must have same number of dimensions

In [218]:
y = np.array([[100],[100]])

In [219]:
y.ndim

2

In [220]:
np.hstack([data, y])

array([[  5,   6,   7, 100],
       [  8,   9,  10, 100]])

In [225]:
data

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [230]:
x

array([1, 2, 3])

In [232]:
z = np.array([1,2])
z

array([1, 2])

In [235]:
np.hstack([data,[[x],[z]]])

array([[5, 6, 7, array([1, 2, 3])],
       [8, 9, 10, array([1, 2])]], dtype=object)

> 배열 분할하기
- np.split, np.hsplit, np.vsplit

In [236]:
x = [1,2,3,100,100,3,2,1]

In [239]:
x1, x2, x3 = np.split(x, [3,5])
x1, x2, x3

(array([1, 2, 3]), array([100, 100]), array([3, 2, 1]))

In [240]:
'''
1. arange(?), reshape(?)
array([[0,1,2,3],
       [4,5,6,7],
       [8,9,10,11],
       [12,13,14,15]])
       
2. up, down = split(?,?)
up 출력시
[[0, 1, 2, 3]]
'''

'\n1. arange(?), reshape(?)\narray([[0,1,2,3],\n       [4,5,6,7],\n       [8,9,10,11],\n       [12,13,14,15]])\n       \n2. up, down = split(?,?)\nup 출력시\n[[0, 1, 2, 3]]\n'

In [261]:
up, down = np.split(np.arange(0,16).reshape(4,4), [1])
up, down

(array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [262]:
up, down = np.hsplit(np.arange(0,16).reshape(4,4), [1])
up

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [263]:
up, down = np.vsplit(np.arange(0,16).reshape(4,4), [1])
up

array([[0, 1, 2, 3]])

In [265]:
# 0으로만 채워진 3x4 행렬
data = np.zeros((3,4), dtype=int)
data

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [270]:
x = np.tile(data, 3)
x.shape, x.ndim

((3, 12), 2)

> 전치 연산
- 2차원 배열의 전치(transpose) 연산은 행과 열을 바꾸는 작업
- 이는 배열의 T 속성으로 구할 수 있음
- 메서드가 아닌 속성

In [271]:
data = np.array([[1, 2, 3], [4, 5, 6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [272]:
data.T.T

array([[1, 2, 3],
       [4, 5, 6]])

> 다차원 배열을 1차원으로 변환하기
1. flatten or  ravel 함수 사용

In [273]:
data = np.arange(1,10,1)
data.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [277]:
data.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 벡터화 연산(vectorized operation)

1.  배열 객체는 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리
- 일반 for 반복문 없이 한번의 연산으로 처리 가능
- 실행 속도도 빠름
- 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

In [ ]:
# 일반 python 배열
data = [0, 1, 2, 3, 4, 5]

In [ ]:
# for 반복문을 사용힌 경우
result = []
for no in data:
    result.append(no*2)
result

> NumPy는 벡터화 연산 사용시 빠른 연산 가능

In [ ]:
x = np.array(data)
x

In [ ]:
x * 2

> 일반 리스트 객체에 정수를 곱하면 객체의 크기가 정수배 만큼으로 증가

In [ ]:
data = [1,2,3]
data * 2

> 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

<!--NAVIGATION-->
<[step02 NumPy 함수 학습](step02_NumpyFun.ipynb) >