# 배열의 연산

### Numpy 자료형

In [1]:
import numpy as np

- numpy 자료형 p120
- default 타입인 float64가 반영되는 함수 : ones()/zeros()
- array()생성시 특정 데이터로 배열 생성, 사용자가 제시한 데이터(타입)는 수정이 안 되게 하는게 기본 마인드

In [2]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [6]:
x = np.array(['a', 'b', 'c'], dtype='U')
x.dtype

dtype('<U1')

In [9]:
# 정수 형태의 데이터로 배열 생성하나 dtype이 유니코드
# 유니코드 저장 및 생성
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [8]:
x

array(['1', '2', '3'], dtype='<U1')

In [10]:
x = np.array([1, 2, 3], dtype='i')
x.dtype

dtype('int32')

In [12]:
x = np.arange(0, 10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x.dtype

dtype('int32')

Inf와 NaN

> 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있음
- 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이  나옴
- 0을 0으로 나누려고 시도하면 np.nan이 나옴

In [14]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

c:\users\playdata\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
c:\users\playdata\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

### 벡터화 연산

1. 벡터화 연산을 쓰면 명시적으로 반복문을 사용하지 않고도 배열의 모든 원소에 대해 반복연산을 할 수 있음
- 장점 : 선형 대수 공식과 동일한 아주 간단한 파이썬 코드를 작성할 수 있음

3. 예시 : 선형 대수에서 두 벡터의 합 구하는 방식

$$ 
x = \begin{bmatrix}1 \\ 2 \\ 3 \\ \vdots \\ 10000 \end{bmatrix}, \;\;\;\;
y = \begin{bmatrix}10001 \\ 10002 \\ 10003 \\ \vdots \\ 20000 \end{bmatrix},
$$
일 때, 두 벡터의 합
$$ z = x + y $$
은 다음과 같이 구한다.
$$
\begin{bmatrix}1 \\ 2 \\ 3 \\ \vdots \\ 10000 \end{bmatrix} + 
\begin{bmatrix}10001 \\ 10002 \\ 10003 \\ \vdots \\ 20000 \end{bmatrix} 
= \begin{bmatrix}1+10001 \\ 2+10002 \\ 3+10003 \\ \vdots \\ 10000+20000 \end{bmatrix}
= \begin{bmatrix}10002 \\ 10004 \\ 10006 \\ \vdots \\ 30000 \end{bmatrix}
$$

4. 만약 벡터화 연산을 사용하지 않는다면 이 연산은 반복문을 사용하여 다음과 같이 구성
5. `%%time`은 셀 코드의 실행시간을 측정하는 IPython 매직 명령.

In [15]:
import numpy as np

In [16]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [17]:
x

array([    1,     2,     3, ...,  9998,  9999, 10000])

In [18]:
y

array([10001, 10002, 10003, ..., 19998, 19999, 20000])

In [73]:
%%time
z = np.zeros_like(x)


Wall time: 499 µs


In [74]:
z

array([0, 0, 0, ..., 0, 0, 0])

In [77]:
%%time
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 7.49 ms


In [78]:
%%timeit
for i in range(10000):
    z[i] = x[i] + y[i]

4.16 ms ± 189 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [76]:
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [37]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

>벡터화 연산을 사용하면 덧셈 연산 하나로 관리
- 선형 대수의 벡터 기호를 사용한 연산과 결과가 완전히 동일
- 연산 속도도 벡터화 연산이 훨씬 빠름

In [59]:
%%time 
z = x + y

ValueError: operands could not be broadcast together with shapes (3,4) (10000,) 

In [39]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

> 사칙 연산뿐 아니라 비교 연산과 같은 논리 연산도 벡터화 연산이 가능

In [41]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [42]:
a

array([1, 2, 3, 4])

In [43]:
b

array([4, 2, 2, 4])

In [44]:
a == b

array([False,  True, False,  True])

In [45]:
a >= b

array([False,  True,  True,  True])

> 배열의 각 원소들 비교가 아닌 배열의 모든 원소가 다 같은지 알고 싶다면 `all` 명령을 사용
> 비교 대상의 각 1차원 배열(벡터)의 같은 인덱스 값 비교

In [20]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [21]:
np.all(a == b)

False

In [22]:
np.all(a == c)

True

## 스칼라와 벡터/행렬의 곱셈

> 스칼라와 벡터/행렬의 곱도 선형 대수에서 사용하는 식과 NumPy 코드가 일치

In [53]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [55]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

## 브로드캐스팅

1. 벡터(또는 행렬)끼리 덧셈 혹은 뺄셈을 하려면 두 벡터(또는 행렬)의 크기가 같아야 함
- 브로드캐스팅(broadcasting)이란? NumPy에서는 서로 다른 크기를 가진 두 배열의 사칙 연산도 지원
- 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞추는 방법
<br><br>

- 규칙<br>
a. 두 배열의 차원수가 다르면 더 작은 수의 차원을 가진 배열 형상의 앞쪽을(왼쪽) 1로 채운다<br>
b. 두 배열의 형상이 어떤 차원에서도 일치하지 않는다면 해당 차원의 형상이 1인 배열이 다른 형상과 일치하도록 늘어난다<br>
c. 임의의 차원에서 크기가 일치하지 않고 1도 아니라면 오류가 발생한다<br>

- 예시 : 다음과 같이 벡터와 스칼라를 더하는 경우

$$ 
x = \begin{bmatrix}0 \\ 1 \\ 2 \\ 3 \\ 4 \end{bmatrix}, \;\;\;\; 
x + 1 = \begin{bmatrix}0 \\ 1 \\ 2 \\ 3 \\ 4 \end{bmatrix} + 1 = ?
$$


- 브로드캐스팅은 다음과 같이 스칼라를 벡터와 같은 크기로 확장시켜서 덧셈 계산

$$ 
\begin{bmatrix}0 \\ 1 \\ 2 \\ 3 \\ 4 \end{bmatrix} + 1 = 
\begin{bmatrix}0 \\ 1 \\ 2 \\ 3 \\ 4 \end{bmatrix} +  \begin{bmatrix}1 \\ 1 \\ 1 \\ 1 \\ 1 \end{bmatrix} = 
\begin{bmatrix}1 \\ 2 \\ 3 \\ 4 \\ 5 \end{bmatrix}
$$

In [23]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [30]:
x = np.vstack([i,i+1,i+2] for i in range(5))
x, type(x)

(array([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]), numpy.ndarray)

In [38]:
[range(7)[0],range(7)[1],range(7)[2]], range(7)[0:0]

([0, 1, 2], range(0, 0))

In [39]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [40]:
x + y

array([1, 2, 3, 4, 5])

In [41]:
x + 1

array([1, 2, 3, 4, 5])

- 브로드캐스팅은 다음처럼 더 차원이 높은 경우에도 적용

$$ 
\begin{bmatrix}0 & 1 & 2 \\ 1 & 2 & 3 \\ 2 & 3 & 4 \\ 3 & 4 & 5 \\ 4 & 5 & 6 \end{bmatrix}
+
\begin{bmatrix}0 \\ 1 \\ 2 \\ 3 \\ 4 \end{bmatrix} 
=
\begin{bmatrix}0 & 1 & 2 \\ 1 & 2 & 3 \\ 2 & 3 & 4 \\ 3 & 4 & 5 \\ 4 & 5 & 6 \end{bmatrix}
+
\begin{bmatrix}0 & 0 & 0 \\ 1 & 1 & 1 \\ 2 & 2 & 2 \\ 3 & 3 & 3 \\ 4 & 4 & 4 \end{bmatrix}
$$

$$ 
\begin{bmatrix}0 & 1 & 2 \\ 1 & 2 & 3 \\ 2 & 3 & 4 \\ 3 & 4 & 5 \\ 4 & 5 & 6 \end{bmatrix}
+
\begin{bmatrix}0 & 1 & 2 \end{bmatrix} 
=
\begin{bmatrix}0 & 1 & 2 \\ 1 & 2 & 3 \\ 2 & 3 & 4 \\ 3 & 4 & 5 \\ 4 & 5 & 6 \end{bmatrix}
+
\begin{bmatrix}0 & 1 & 2 \\ 0 & 1 & 2 \\ 0 & 1 & 2 \\ 0 & 1 & 2 \\ 0 & 1 & 2 \end{bmatrix} 
$$

In [98]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [99]:
x.ndim

2

In [100]:
x.shape

(5, 3)

In [52]:
# 차원 자체를 추가하는 속성
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [58]:
x, x + y

(array([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]), array([[ 0,  1,  2],
        [ 2,  3,  4],
        [ 4,  5,  6],
        [ 6,  7,  8],
        [ 8,  9, 10]]))

In [50]:
y = np.arange(5).reshape(5,1)
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [102]:
y.ndim

2

In [103]:
y.shape

(5, 1)

In [44]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [45]:
y = np.arange(3)
y

array([0, 1, 2])

In [28]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

## 차원 축소 연산(집계)

1. 행렬의 하나의 행에 있는 원소들을 하나의 데이터 집합으로 보고 그 집합의 평균을 구하면 각 행에 대해 하나의 숫자가 나오게 된다. 
 <br>
 예 : 10x5 크기의 2차원 배열에 대해 행-평균을 구하면 10개의 숫자를 가진 1차원 벡터가 생성(차원 축소(dimension reduction) 연산)
 <br><br>

2. NumPy는 다음과 같은 차원 축소 연산 명령 혹은 메서드를 지원<br><br>
a. 최대/최소: min, max, argmin(최소값의 index), argmax(최대값의 index)<br>
b. 통계: sum(합계), mean(평균), median(중앙값), std(표준 편처 계산), var(분산)<br>
c. 불리언: all(모든 요소가 참인지 검사), any(요소 중 참이 있는지 검사)<br>

3. 중앙값<br>
a. 존재하는 데이터의 가운데값?<br>
b. 오름차순으로 정렬시킨 데이터의 가운데값?


In [59]:
x = np.array([1, 2, 3, 4])


array([1, 2, 3, 4])

In [63]:
type(x), x.sum(), x.min(), x.max(), x.argmin(), x.argmax()

(numpy.ndarray, 10, 1, 4, 0, 3)

In [65]:
np.median(x)
'''
짝수면 오름차순 정렬후 가운데두값+/2
홀수면 오름차순 정렬후 가운데값
'''

'\n짝수면 오름차순 정렬후 가운데두값+/2\n홀수면 오름차순 정렬후 가운데값\n'

In [68]:
x.sum()/len(x), x.mean()

(2.5, 2.5)

> 연산의 대상이 2차원 이상인 경우
1. 어느 차원으로 계산을 할 지를 axis 인수 사용
- axis=0인 경우는 열끼리 연산(디폴트)
- axis=1인 경우는 행끼리 연산 
- axis 인수는 대부분의 차원 축소 명령에 적용할 수 있음

In [70]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [77]:
x.sum(axis=0).shape, x.sum(axis=1).shape

((2,), (2,))

In [79]:
x = np.array([[[1,1,1],[2,2,2]], [[3,3,3],[4,4,4]]])
x, x.shape

(array([[[1, 1, 1],
         [2, 2, 2]],
 
        [[3, 3, 3],
         [4, 4, 4]]]), (2, 2, 3))

In [84]:
x.sum(axis=0).shape, x.sum(axis=1).shape, x.sum(axis=2).shape, x.sum(axis=0), x.sum(axis=1), x.sum(axis=2)

((2, 3), (2, 3), (2, 2), array([[4, 4, 4],
        [6, 6, 6]]), array([[3, 3, 3],
        [7, 7, 7]]), array([[ 3,  6],
        [ 9, 12]]))

## 정렬

1. sort명령이나 메서드를 사용하여 배열 안의 원소를 크기에 따라 정렬하여 새로운 배열 구성
- 2차원 이상인 경우에는 행이나 열을 각각 따로따로 정렬하는데 `axis` 인수를 사용하여 행을 정렬할 것인지 열을 정렬한 것인지 결정
- axis=0 이면 각각의 행을 따로따로 정렬하고 axis=1이면 각각의 열을 따로따로 정렬
- 디폴트 값은 -1 즉 가장 안쪽(나중)의 차원

In [102]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [103]:
a.shape

(3, 4)

In [104]:
np.sort(a, axis=1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [114]:
# 각 row별 자체 정렬(오름차순) 정렬을 위한 axis=?
# 2차원 내부에 존재하는 모든 데이터들을 오름차순으로 정렬하는 기준의 axis=?
# 2번 문제를 자기주도로 재 정리하셔서 답안도 도출
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [119]:
a.flatten().sort().reshape(3,4)

AttributeError: 'NoneType' object has no attribute 'reshape'

In [127]:
a = np.array([42, 38, 12, 25])# 0 1 2 3
data = np.argsort(a)
data

array([2, 3, 1, 0], dtype=int64)

In [128]:
a[data], a

(array([12, 25, 38, 42]), array([42, 38, 12, 25]))

In [133]:
-np.sort(-a), a

(array([42, 38, 25, 12]), array([42, 38, 12, 25]))